# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Manifest"
license = "MIT"
licenselink = "https://github.com/goopyflux/manifest/blob/master/LICENSE.md"
description = "A clean, responsive theme for Hugo"
homepage = "http://siteforthistheme.com/"
tags = ["", ""]
features = ["", ""]
min_version = 0.15

[author]
  name = "goopy flux"
  homepage = "https://goopyflux.github.io/"

